# ETAPA 1: Construcción (Build)
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copiamos el pom y descargamos dependencias (Caché de capas)
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiamos el código fuente y compilamos
COPY src ./src
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Run)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copiamos solo el JAR generado en la etapa anterior
COPY --from=build /app/target/micro-eureka-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto
EXPOSE 8761

# Comando de arranque
ENTRYPOINT ["java", "-jar", "app.jar"]